---
kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push-devfu
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore
  tags:
    - amd64
    
# - name: build-push-dockerhub
#   image: plugins/docker
#   settings:
#     username:
#       from_secret: dockerHubUserName
#     password:
#       from_secret: dockerHubPassword
#     repo: fuzzyoni/smore
#     tags:
#       - amd64

---
kind: pipeline
name: build-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build-push-devfu
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore
  tags:
    - arm64
    
# - name: build-push-dockerhub
#   image: plugins/docker
#   settings:
#     username:
#       from_secret: dockerHubUserName
#     password:
#       from_secret: dockerHubPassword
#     repo: fuzzyoni/smore
#     tags:
#       - arm64
      
depends_on:
- build-amd64
