---

kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build-push-devfu
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore
    tags:
      - amd64
    
---

kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: build-push-devfu
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore
    tags:
      - arm64
    
