---
kind: pipeline
type: docker
name: private

platform:
  os: linux
  arch: amd64

steps:
- name: smore
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore

---
kind: pipeline
type: docker
name: public

platform:
  os: linux
  arch: amd64

- name: smore
  image: plugins/docker
  settings:
    username:
      from_secret: DH_USERNAME
    password:
      from_secret: DH_PASSWORD
    repo: fuzzyoni/smore
