---

kind: pipeline
type: docker
name: build-arm64

steps:
- name: smore-arm64
  image: plugins/docker:linux-arm64
  settings:
    repo: reg.devfu.net/smore
    tags:
      - arm64

node:
  arch: arm64

---

kind: pipeline
type: docker
name: build-amd64

steps:
- name: smore-amd64
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore
    tags:
      - amd64

node:
  arch: amd64

