---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: golang:latest
  commands:
    - mkdir -p $GOPATH/src/git.lan.toefu.net/fuzzy
    - ln -sf $PWD $GOPATH/src/git.lan.toefu.net/fuzzy/smore
    - cd $GOPATH/src/git.lan.toefu.net/fuzzy/smore
    - go get -d .
    - go build -v .

