---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64
  
clone:
  disable: true

steps:
- name: clone
  image: alpine
  commands:
  - apk update
  - apk add go git
  - git clone https://github.com/octocat/hello-world.git .
  - git checkout $DRONE_COMMIT

- name: build
  commands:
  - go build
  - go test

trigger:
  branch:
  - master
  event:
  - push
