---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64
  
clone:
  disable: true

steps:
- name: clone
  image: golang:alpine
  commands:
  - apk update
  - apk add go git
  - git clone https://github.com/octocat/hello-world.git .
  - git checkout $DRONE_COMMIT

- name: build
  commands:
  - go build
  - go test

- name: image
  image: plugins/docker
  repo: reg.devfu.net/smore:arm64
