---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: smore
  image: plugins/docker
  settings:
    username:
      from_secret: DH_USERNAME
    password:
      from_secret: DH_PASSWORD
    repo: fuzzyoni/smore
