---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64
  
clone:
  disable: true

steps:
- name: clone
  image: golang:alpine
  commands:
  - apk update
  - apk add go git
  - git clone https://github.com/octocat/hello-world.git .
  - git checkout $DRONE_COMMIT

- name: build
  image: golang:alpine
  commands:
  - go build
  - go test

- name: docker  
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore:arm64

trigger:
  branch:
  - master
  event:
  - push
