---
kind: pipeline
type: docker
name: build
steps:
- name: smore-local
  image: plugins/docker
  settings:
    repo: reg.devfu.net/smore

---
kind: pipeline
type: docker
name: build
steps:
- name: smore-dockerhub
  image: plugins/docker
  settings:
    username:
      from_secret: DH_USERNAME
    password:
      from_secret: DH_PASSWORD
    repo: fuzzyoni/smore
